"""Initial migration

Revision ID: 2b7ebe0a0e95
Revises: 
Create Date: 2025-08-17 21:04:30.323868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b7ebe0a0e95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('company_phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('company_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('about', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_companies_company_email'), 'companies', ['company_email'], unique=False, schema='public')
    op.create_index(op.f('ix_public_companies_company_name'), 'companies', ['company_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_companies_created_at'), 'companies', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_companies_updated_at'), 'companies', ['updated_at'], unique=False, schema='public')
    op.create_table('blogs',
    sa.Column('blog_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['public.companies.company_id'], ),
    sa.PrimaryKeyConstraint('blog_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_blogs_created_at'), 'blogs', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_blogs_updated_at'), 'blogs', ['updated_at'], unique=False, schema='public')
    op.create_table('chats',
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('chat_to', sa.Uuid(), nullable=True),
    sa.Column('chat_from', sa.Uuid(), nullable=True),
    sa.Column('chat_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chat_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chat_from'], ['public.companies.company_id'], ),
    sa.ForeignKeyConstraint(['chat_to'], ['public.companies.company_id'], ),
    sa.PrimaryKeyConstraint('chat_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_chats_chat_timestamp'), 'chats', ['chat_timestamp'], unique=False, schema='public')
    op.create_index(op.f('ix_public_chats_created_at'), 'chats', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_chats_updated_at'), 'chats', ['updated_at'], unique=False, schema='public')
    op.create_table('clients',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('client_username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('client_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('client_phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('client_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('client_role_in_company', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['public.companies.company_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_clients_client_email'), 'clients', ['client_email'], unique=False, schema='public')
    op.create_index(op.f('ix_public_clients_client_name'), 'clients', ['client_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_clients_client_username'), 'clients', ['client_username'], unique=False, schema='public')
    op.create_index(op.f('ix_public_clients_created_at'), 'clients', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_clients_updated_at'), 'clients', ['updated_at'], unique=False, schema='public')
    op.create_table('collaborations',
    sa.Column('collaboration_id', sa.Uuid(), nullable=False),
    sa.Column('collaboration_from', sa.Uuid(), nullable=True),
    sa.Column('collaboration_to', sa.Uuid(), nullable=True),
    sa.Column('collaboration_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_from'], ['public.companies.company_id'], ),
    sa.ForeignKeyConstraint(['collaboration_to'], ['public.companies.company_id'], ),
    sa.PrimaryKeyConstraint('collaboration_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_collaborations_created_at'), 'collaborations', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_collaborations_updated_at'), 'collaborations', ['updated_at'], unique=False, schema='public')
    op.create_table('notifications',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notification_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('notification_from', sa.Uuid(), nullable=True),
    sa.Column('notification_to', sa.Uuid(), nullable=True),
    sa.Column('notification_timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notification_read_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notification_priority', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['public.companies.company_id'], ),
    sa.ForeignKeyConstraint(['notification_from'], ['public.companies.company_id'], ),
    sa.ForeignKeyConstraint(['notification_to'], ['public.companies.company_id'], ),
    sa.PrimaryKeyConstraint('notification_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_notifications_created_at'), 'notifications', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_notifications_notification_read_at'), 'notifications', ['notification_read_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_notifications_notification_timestamp'), 'notifications', ['notification_timestamp'], unique=False, schema='public')
    op.create_index(op.f('ix_public_notifications_updated_at'), 'notifications', ['updated_at'], unique=False, schema='public')
    op.create_table('projects',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tools', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metrics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['public.companies.company_id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_projects_created_at'), 'projects', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_projects_updated_at'), 'projects', ['updated_at'], unique=False, schema='public')
    op.create_table('services',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['public.companies.company_id'], ),
    sa.PrimaryKeyConstraint('service_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_services_created_at'), 'services', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_services_updated_at'), 'services', ['updated_at'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_services_updated_at'), table_name='services', schema='public')
    op.drop_index(op.f('ix_public_services_created_at'), table_name='services', schema='public')
    op.drop_table('services', schema='public')
    op.drop_index(op.f('ix_public_projects_updated_at'), table_name='projects', schema='public')
    op.drop_index(op.f('ix_public_projects_created_at'), table_name='projects', schema='public')
    op.drop_table('projects', schema='public')
    op.drop_index(op.f('ix_public_notifications_updated_at'), table_name='notifications', schema='public')
    op.drop_index(op.f('ix_public_notifications_notification_timestamp'), table_name='notifications', schema='public')
    op.drop_index(op.f('ix_public_notifications_notification_read_at'), table_name='notifications', schema='public')
    op.drop_index(op.f('ix_public_notifications_created_at'), table_name='notifications', schema='public')
    op.drop_table('notifications', schema='public')
    op.drop_index(op.f('ix_public_collaborations_updated_at'), table_name='collaborations', schema='public')
    op.drop_index(op.f('ix_public_collaborations_created_at'), table_name='collaborations', schema='public')
    op.drop_table('collaborations', schema='public')
    op.drop_index(op.f('ix_public_clients_updated_at'), table_name='clients', schema='public')
    op.drop_index(op.f('ix_public_clients_created_at'), table_name='clients', schema='public')
    op.drop_index(op.f('ix_public_clients_client_username'), table_name='clients', schema='public')
    op.drop_index(op.f('ix_public_clients_client_name'), table_name='clients', schema='public')
    op.drop_index(op.f('ix_public_clients_client_email'), table_name='clients', schema='public')
    op.drop_table('clients', schema='public')
    op.drop_index(op.f('ix_public_chats_updated_at'), table_name='chats', schema='public')
    op.drop_index(op.f('ix_public_chats_created_at'), table_name='chats', schema='public')
    op.drop_index(op.f('ix_public_chats_chat_timestamp'), table_name='chats', schema='public')
    op.drop_table('chats', schema='public')
    op.drop_index(op.f('ix_public_blogs_updated_at'), table_name='blogs', schema='public')
    op.drop_index(op.f('ix_public_blogs_created_at'), table_name='blogs', schema='public')
    op.drop_table('blogs', schema='public')
    op.drop_index(op.f('ix_public_companies_updated_at'), table_name='companies', schema='public')
    op.drop_index(op.f('ix_public_companies_created_at'), table_name='companies', schema='public')
    op.drop_index(op.f('ix_public_companies_company_name'), table_name='companies', schema='public')
    op.drop_index(op.f('ix_public_companies_company_email'), table_name='companies', schema='public')
    op.drop_table('companies', schema='public')
    # ### end Alembic commands ###
